# Release workflow: packages repo and creates a tag based on version number when pushed to main

name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  VERSION: "0.3.4"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Package repository
        run: |
          zip -r QuackPack-ParallaxContinued_${{ env.VERSION }}.zip . -x '*.git*' -x '*.github*'

      - name: Create and push tag
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          files: |
            QuackPack-ParallaxContinued_${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}